version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-35-169-254-43.compute-1.amazonaws.com
            database: dc9mfj585f8n4j
            user: uicfdsvtcixiol
            password: f2c838ad2071937be6fe76f10b8b6a3375c53ba2f66a45608b14d9f00470de46
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true